### PR TITLE
Creating backend.env file

### PR DESCRIPTION
**Pull request by Amiele2006**
making a .env file

### CODE REVIEW

**Comment by alexindevs** [comment]
Hey. How's this going? Are you through?

**Comment by ifedayoprince** [comment]
@Amiele2006, let me do it now.

**Comment by ifedayoprince** [comment]
@alexindevs Do you think what should be in the .env?

**Comment by Amiele2006** [comment]
I tried creating the file and set a PR but it was not approved

**Comment by alexindevs** [comment]
> @alexindevs Do you think what should be in the .env?

For now, not so sure. Maybe the environment being set to development?

**Pull request closed without merging**
